name: CI/CD for Movie-Market App

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/movie-market .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/movie-market
